### ISSUE TITLE
GREAT CART

### ISSUE THREAD

**Issue by troiweb** [seikan/Cart#9]
Only small remark ///
This is not working - itemMaxQuantity' => 99,  // 0 = Unlimited
When set to 0 - it is really zero.

**Comment by seikan** [comment]
This issue already been fixed.
Can you make sure you are using the latest codes?

**Comment by troiweb** [comment]
GREAT. 
Sorry, i just downloaded 3 days ago. Seems you fixed it 2 days ago!
Thank you very much!

**Comment by seikan** [comment]
Perfect :)
